name: learn_europe
description: "An educational app for discovering the european continent"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  # Dependency injection
  get_it: ^7.7.0

  # Svg Support
  flutter_svg: ^2.0.10+1

  # Animated Digits
  animated_digit: ^3.2.3

  # Confetti
  confetti: ^0.7.0

  # Firebase Integration
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1

  # TextToSpeech
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Analyzer
  flutter_lints: ^4.0.0

  # State Management
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/
