name: learn_europe
description: "An educational app for discovering the european continent"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  # Svg Support
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Analyzer
  flutter_lints: ^3.0.0

  # State Management
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/

